apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts 
    #selector app:posts letting it know which pods (find all pods with label app:posts - look in depl.yaml) to expose to outside world
    ports:
      - name: posts
        protocol: TCP
        port: 4000
        targetPort: 4000